### ISSUE TITLE
Use Nerdfetch for screenshots

### ISSUE THREAD

**Issue by ThatOneCalculator** [marcelovbcfilho/black-box#1]
Thank you so much for making these themes! For terminal screenshots, we prefer to use [Nerdfetch](https://codeberg.org/thatonecalculator/nerdfetch) as the fetch script. Here are some screenshots if you want to use them:

![image](https://user-images.githubusercontent.com/44733677/195908926-559310c7-98a6-496c-ad3a-c23e8f19c123.png)

![image](https://user-images.githubusercontent.com/44733677/195908995-50a3fb3d-4b18-4bcf-958c-3463a6024357.png)

![image](https://user-images.githubusercontent.com/44733677/195909099-fcbe3759-d05b-4c1d-a3fb-b4294330356d.png)

**Comment by marcelovbcfilho** [comment]
I didn't knew about this, already updated the master with the nerdfetch screenshots.

Fixed on fe17382f35a4e3c1001f3f57f735feab0a1ad50f
